### ISSUE TITLE
[arabic/arab-fa]  Roozbeh's feedback

### ISSUE THREAD

**Issue by roozbehp** [r12a/scripts#102]
[source] https://r12a.github.io/scripts/arabic/arab-fa

A few random comments:
You are including ɣ and q in the chart, which doesn't make sense to me. In Tehrani standard Persian (as well as several Northern Iran pronunciations), you only have one phoneme, ɢ. In Central and Southern Iran, you have two phonemes, either ɣ and q, or ɣ and ɢ.

Also, it's unclear why the glottal stop is grayed out. It clearly exists in coda positions in standard Persian in several words, such as /ʃejʔ/ or /ʃeʔr/. Most linguists believe it also exists in onset position, starting most words starting with alef.

Since it looks like you'd be covering Afghan Persian too, you may want to talk about its two extra vowels too (these used to exist in standard Iranian Persian too, but have merged into the other vowels).

You mention that ه can sound like /h/ and /e/, but it also has /æ/, at the end of the very common word, /næ/ نه (“no”).

You talk about the combination U+06CC ARABIC LETTER FARSI YEH + U+0654 ARABIC HAMZA ABOVE. That is not supposed to be used at all. One should use U+0626 instead.

Quotation marks are never “” in good quality Persian texts. They are «», with rounded form of the guillemets preferred.

**Comment by r12a** [comment]
Thanks @roozbehp.

> You are including ɣ and q in the chart, which doesn't make sense to me. In Tehrani standard Persian (as well as several Northern Iran pronunciations), you only have one phoneme, ɢ. In Central and Southern Iran, you have two phonemes, either ɣ and q, or ɣ and ɢ.

Yes. The sources i had weren't super clear about that.  I checked some things, and removed the q from the phoneme table. I still see both ɣ and ɢ in the IPA transcriptions of ق and غ in terms i found in Wiktionary (see https://r12a.github.io/scripts/arabic/fa_vocab?q=%D9%82|%D8%BA, 3rd column).

> Also, it's unclear why the glottal stop is grayed out. It clearly exists in coda positions in standard Persian in several words, such as /ʃejʔ/ or /ʃeʔr/. Most linguists believe it also exists in onset position, starting most words starting with alef.

Yes, that was a mistake. Now fixed.
 
> Since it looks like you'd be covering Afghan Persian too, you may want to talk about its two extra vowels too (these used to exist in standard Iranian Persian too, but have merged into the other vowels).

This page is focused on Iranian Persian.  I may get to Afghan Persian at some point, but will create a new page for it.

> You mention that ه can sound like /h/ and /e/, but it also has /æ/, at the end of the very common word, /næ/ نه (“no”).

Yes, actually i do mention that in the detailed character-by-character notes (see https://r12a.github.io/scripts/arabic/block#fa064E), but it didn't make it into the overview. (You can see the detail if you click on the FATHA in the yellow box at https://r12a.github.io/scripts/arabic/arab-fa#vowelDiacritics) .

However, given your comment, i added it to the main text, too.

> You talk about the combination U+06CC ARABIC LETTER FARSI YEH + U+0654 ARABIC HAMZA ABOVE. That is not supposed to be used at all. One should use U+0626 instead.

I'm going to open this as a separate comment, because there's lots to be said here, and it fits with some stuff i'm planning to do for SAH.

> Quotation marks are never “” in good quality Persian texts. They are «», with rounded form of the guillemets preferred.

That was an oversight. Now fixed.
