### ISSUE TITLE
[arabic/kashmiri]  Jazm incorrect rendering

### ISSUE THREAD

**Issue by Rishabhbhat** [r12a/scripts#103]
[source] https://r12a.github.io/scripts/arabic/kashmiri

The jazm does not render properly for example with the text "فرینٛچ اوپَن".

**Comment by r12a** [comment]
It's hard to know for certain what the problem is, since you didn't mention the font you're using or show a picture of how the rendering looks, but i imagine that you're seeing something like this when you use the Noto Nastaliq Urdu font.

![Screenshot 2021-09-03 at 10 06 37](https://user-images.githubusercontent.com/4839211/131980453-b1cd89c4-b1d7-4805-a4df-712da58efb77.png)


Your problem is almost certainly because you are using the wrong Unicode character for the jazm.  Your example uses 

ٛ U+065B: ARABIC VOWEL SIGN INVERTED SMALL V ABOVE

for which there is not even a glyph in, for example, the Noto Nastaliq Urdu font.

Try using ْ U+0652: ARABIC SUKUN​ instead, with a font that produces the correct shape.

Just by making that change, you will then see something like

![Screenshot 2021-09-03 at 10 02 40](https://user-images.githubusercontent.com/4839211/131980045-71e34f27-f713-46d1-85f3-6d5e79d90464.png)

This is explained here https://r12a.github.io/scripts/arabic/kashmiri#confusables, and is why the article uses U+0652 for examples of the jazm at https://r12a.github.io/scripts/arabic/kashmiri#confusables

hope that helps

**Comment by Rishabhbhat** [comment]
You're right, that was indeed the one being used. Thank you very much for the prompt response.
