### ISSUE TITLE
Sharada Font

### ISSUE THREAD

**Issue by virtualvinodh** [r12a/scripts#110]
Currently, https://r12a.github.io/scripts/fontlist/?script=shrd#result lists only Noto Sans Sharada.

Could you also add https://github.com/virtualvinodh/satisarsharada ?

V

**Comment by r12a** [comment]
hello Vinodh, Thanks for the suggestion, but the fonts listed on that page are, by design, only those that "are available via the Windows 10 and Mac OS X operating systems, as well as Google's Noto fonts and SIL fonts". The intention is that one can tell what text would look like if only system fonts are available.  I stretched it a little to include the readily available Noto and SIL fonts, but don't have the bandwidth to go beyond that.
