### ISSUE TITLE
[hebrew/block] yod triangle lacks a category

### ISSUE THREAD

**Issue by bdenckla** [r12a/scripts#159]
[source] https://r12a.github.io/scripts/hebr/block.html

Currently it lacks a category, whereas most other marks are categorized as Israeli Hebrew or Biblical Hebrew (or in one case, (_pe_), both).

I can say with some certainty that it is neither Biblical Hebrew nor Israeli Hebrew.

I have some vague recollection that it may appear in praybooks. So I don't know what to call that. Perhaps Liturgical Hebrew. If indeed I am correct about it appearing in prayerbooks.

**Comment by r12a** [comment]
Yes, if i don't have any information to post about a character i leave the notes blank. It stays in the block.html file so that all characters have an entry stub - and carry Unicode descriptions, links to UniView, etc.

Btw, i also change the Biblical Hebrew headings to Miscellaneous Other, until such time as i do an in-depth study of biblical Hebrew, at which point i'll create a whole new set of orthography materials and create a new set of Biblical Hebrew titles.
