### ISSUE TITLE
[fontlist] Two problems with the Noto Sans Warang Citi sample image

### ISSUE THREAD

**Issue by dscorbett** [r12a/scripts#89]
notosanswarangciti.png includes some .notdef glyphs and the final glyph is truncated.

**Comment by r12a** [comment]
yes, that's all intentional.  The images are all exactly 680 pixels wide, so pretty much all languages have the text cut off.  (If you want to see the full text, and have the font, click on Show using fonts available on this computer) (or use https://r12a.github.io/scripts/samples/?script=wara#result)

The .notdef glyphs are also intentional. They hide glyphs that are not in the font, so that you can be sure that the glyphs you are seeing are from the font you wanted to look at.

The latter point is explained in the Notes. Perhaps i should add something about the image dimensions

Anyway, i think that hopefully addresses your concerns, so i'll close this. Reopen if you want.
